language: node_js
node_js:
- node

services:
- postgresql

before_script:
- psql -c 'create database edamam_microservice_database_test;' -U postgres
- sequelize db:migrate --env test

script:
- npm install

after_script:
- npm test
